<?php
/**
 * Plugin Name: Elementize
 * Description: Controlled REST access to WordPress, Elementor, and Pixfort.
 * Version: 0.2.3
 * Requires at least: 6.5
 * Requires PHP: 8.0
 * Requires Plugins: elementor
 * Author: Mazbac
 * License: GPL-2.0-or-later
 */
if ( ! defined( 'ABSPATH' ) ) exit;

if ( ! class_exists( 'Elementize_Plugin', false ) ) {
final class Elementize_Plugin {
	private const VERSION='0.2.3', NS='elementize/v1', MAX_TEXT=20000, MAX_UPDATES=100;

	public static function init(): void { add_action('rest_api_init',[self::class,'routes']); add_action('admin_menu',[self::class,'menu']); }
	public static function menu(): void { add_menu_page('Elementize','Elementize','manage_options','elementize',[self::class,'admin'],'dashicons-admin-tools',58); }
	public static function admin(): void {
		if(!current_user_can('manage_options')) return;
		$el=class_exists('\\Elementor\\Plugin'); $px=self::pixfort_info(); $theme=wp_get_theme(); $lib=file_exists(self::library_loader());
		?>
		<div class="wrap"><h1>Elementize</h1><p>Controlled WordPress, Elementor, and Pixfort access for conversational tools.</p>
		<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px;max-width:1000px;margin-top:20px;">
		<?php self::card('Elementize',true,'Version '.self::VERSION); self::card('Elementor',$el,$el&&defined('ELEMENTOR_VERSION')?'Version '.ELEMENTOR_VERSION:'Not detected'); self::card('Pixfort Core',$px['active'],$px['active']?trim($px['name'].' '.$px['version']):'Not detected'); self::card('Pixfort Library',$lib,$lib?'Catalogue source detected':'Catalogue source not detected'); self::card('REST API',true,'Endpoints registered'); ?>
		</div><div class="card" style="max-width:1000px;margin-top:20px;padding:20px;"><h2 style="margin-top:0">Environment</h2><table class="widefat striped"><tbody>
		<tr><td><strong>WordPress</strong></td><td><?php echo esc_html(get_bloginfo('version')); ?></td></tr><tr><td><strong>Theme</strong></td><td><?php echo esc_html(trim($theme->get('Name').' '.$theme->get('Version'))); ?></td></tr>
		<tr><td><strong>Pixfort catalogue endpoint</strong></td><td><code><?php echo esc_html(rest_url(self::NS.'/pixfort/templates')); ?></code></td></tr><tr><td><strong>Pixfort insert endpoint</strong></td><td><code><?php echo esc_html(rest_url(self::NS.'/pages/{id}/pixfort/insert')); ?></code></td></tr>
		</tbody></table></div><div class="card" style="max-width:1000px;margin-top:20px;padding:20px;"><h2 style="margin-top:0">Current test state</h2><p><strong>Copy editing and Pixfort catalogue access are proven.</strong> 0.2.3 fixes plugin bootstrap and keeps the guarded append-at-end Pixfort insertion operation.</p></div></div><?php
	}
	private static function card(string $label,bool $ok,string $detail): void { $bg=$ok?'#edfaef':'#fcf0f1';$c=$ok?'#116329':'#8a2424';$t=$ok?'Detected':'Attention'; echo '<div class="card" style="margin:0;padding:20px"><div style="display:flex;justify-content:space-between"><h2 style="margin:0">'.esc_html($label).'</h2><span style="padding:4px 8px;border-radius:999px;background:'.esc_attr($bg).';color:'.esc_attr($c).';font-weight:600">'.esc_html($t).'</span></div><p style="margin-bottom:0">'.esc_html($detail).'</p></div>'; }

	private static function pixfort_info(): array {
		if(!function_exists('get_plugins')) require_once ABSPATH.'wp-admin/includes/plugin.php';
		$a=(array)get_option('active_plugins',[]); if(is_multisite()) $a=array_merge($a,array_keys((array)get_site_option('active_sitewide_plugins',[]))); $p=get_plugins();
		foreach(array_unique($a) as $f){$d=$p[$f]??[];$n=(string)($d['Name']??''); if(stripos($f,'pixfort-core')===false&&stripos($n,'pixfort core')===false) continue; return ['active'=>true,'name'=>$n?:'Pixfort Core','version'=>(string)($d['Version']??'')];}
		return ['active'=>false,'name'=>'','version'=>''];
	}

	public static function routes(): void {
		register_rest_route(self::NS,'/status',['methods'=>WP_REST_Server::READABLE,'callback'=>[self::class,'status'],'permission_callback'=>[self::class,'can_access']]);
		register_rest_route(self::NS,'/pages',['methods'=>WP_REST_Server::READABLE,'callback'=>[self::class,'pages'],'permission_callback'=>[self::class,'can_access'],'args'=>['page'=>['type'=>'integer','default'=>1,'minimum'=>1,'sanitize_callback'=>'absint'],'per_page'=>['type'=>'integer','default'=>50,'minimum'=>1,'maximum'=>100,'sanitize_callback'=>'absint']]]);
		register_rest_route(self::NS,'/pixfort/templates',['methods'=>WP_REST_Server::READABLE,'callback'=>[self::class,'templates'],'permission_callback'=>[self::class,'can_manage_pixfort'],'args'=>['type'=>['type'=>'string','default'=>'section','sanitize_callback'=>'sanitize_key'],'q'=>['type'=>'string','default'=>'','sanitize_callback'=>'sanitize_text_field'],'category'=>['type'=>'string','default'=>'','sanitize_callback'=>'sanitize_key'],'page'=>['type'=>'integer','default'=>1,'minimum'=>1,'sanitize_callback'=>'absint'],'per_page'=>['type'=>'integer','default'=>50,'minimum'=>1,'maximum'=>100,'sanitize_callback'=>'absint']]]);
		register_rest_route(self::NS,'/pages/(?P<id>\\d+)/pixfort/insert',['methods'=>WP_REST_Server::EDITABLE,'callback'=>[self::class,'insert_template'],'permission_callback'=>[self::class,'can_manage_pixfort_page'],'args'=>['id'=>['type'=>'integer','required'=>true,'sanitize_callback'=>'absint'],'content_hash'=>['type'=>'string','required'=>true],'template_id'=>['type'=>'string','required'=>true,'sanitize_callback'=>'sanitize_key']]]);
		register_rest_route(self::NS,'/pages/(?P<id>\\d+)/text',[
			['methods'=>WP_REST_Server::READABLE,'callback'=>[self::class,'page_text'],'permission_callback'=>[self::class,'can_edit_page'],'args'=>['id'=>['type'=>'integer','required'=>true,'sanitize_callback'=>'absint']]],
			['methods'=>WP_REST_Server::EDITABLE,'callback'=>[self::class,'update_text'],'permission_callback'=>[self::class,'can_edit_page'],'args'=>['id'=>['type'=>'integer','required'=>true,'sanitize_callback'=>'absint'],'content_hash'=>['type'=>'string','required'=>true],'updates'=>['type'=>'array','required'=>true]]]
		]);
	}
	public static function can_access(){ if(!is_user_logged_in())return new WP_Error('elementize_auth_required','Authentication is required.',['status'=>401]); if(!current_user_can('edit_pages'))return new WP_Error('elementize_forbidden','The authenticated WordPress user cannot edit pages.',['status'=>403]); return true; }
	public static function can_manage_pixfort(){ if(!is_user_logged_in())return new WP_Error('elementize_auth_required','Authentication is required.',['status'=>401]); if(!current_user_can('manage_options'))return new WP_Error('elementize_pixfort_forbidden','Pixfort library access requires an administrator.',['status'=>403]); return true; }
	public static function can_edit_page(WP_REST_Request $r){$x=self::can_access();return is_wp_error($x)?$x:self::page_permission($r);}
	public static function can_manage_pixfort_page(WP_REST_Request $r){$x=self::can_manage_pixfort();return is_wp_error($x)?$x:self::page_permission($r);}
	private static function page_permission(WP_REST_Request $r){$id=absint($r['id']);$p=get_post($id);if(!$p||$p->post_type!=='page')return new WP_Error('elementize_page_not_found','Page not found.',['status'=>404]);if(!current_user_can('edit_post',$id))return new WP_Error('elementize_forbidden','The authenticated WordPress user cannot edit this page.',['status'=>403]);return true;}

	public static function status(): WP_REST_Response {$p=self::pixfort_info();$t=wp_get_theme();return new WP_REST_Response(['elementize_version'=>self::VERSION,'wordpress_version'=>get_bloginfo('version'),'elementor_loaded'=>class_exists('\\Elementor\\Plugin'),'elementor_version'=>defined('ELEMENTOR_VERSION')?ELEMENTOR_VERSION:null,'pixfort_loaded'=>$p['active'],'pixfort_name'=>$p['active']?$p['name']:null,'pixfort_version'=>$p['active']?$p['version']:null,'pixfort_library_detected'=>file_exists(self::library_loader()),'pixfort_source_detected'=>file_exists(self::source_path()),'theme'=>$t->get('Name'),'theme_version'=>$t->get('Version')],200);}
	public static function pages(WP_REST_Request $r){if(!class_exists('\\Elementor\\Plugin'))return self::el_missing();$page=max(1,absint($r->get_param('page')));$pp=min(100,max(1,absint($r->get_param('per_page'))));$q=new WP_Query(['post_type'=>'page','post_status'=>array_keys(get_post_stati(['internal'=>false])),'perm'=>'editable','posts_per_page'=>$pp,'paged'=>$page,'orderby'=>'modified','order'=>'DESC']);$out=[];foreach($q->posts as $p){if(!current_user_can('edit_post',$p->ID))continue;$d=self::doc($p->ID);$is=$d&&$d->is_built_with_elementor();$out[]=['id'=>$p->ID,'title'=>get_the_title($p),'status'=>$p->post_status,'modified_gmt'=>$p->post_modified_gmt,'url'=>get_permalink($p),'is_elementor'=>(bool)$is,'elementor_edit_url'=>$is?$d->get_edit_url():null];}return new WP_REST_Response(['page'=>$page,'per_page'=>$pp,'total'=>(int)$q->found_posts,'total_pages'=>(int)$q->max_num_pages,'pages'=>$out],200);}

	public static function templates(WP_REST_Request $r){$lib=self::library();if(is_wp_error($lib))return $lib;$type=strtolower((string)$r->get_param('type'))?:'section';if(!in_array($type,['section','page','all'],true))return new WP_Error('elementize_invalid_pixfort_type','Pixfort type must be section, page, or all.',['status'=>400]);$q=strtolower(trim((string)$r->get_param('q')));$cat=strtolower(trim((string)$r->get_param('category')));$page=max(1,absint($r->get_param('page')));$pp=min(100,max(1,absint($r->get_param('per_page'))));$all=[];if($type==='section'||$type==='all')self::append_templates($all,$lib['sections']??[],'section');if($type==='page'||$type==='all')self::append_templates($all,$lib['pages']??[],'page');$f=[];foreach(array_values($all) as $x){$cats=array_map('strtolower',$x['categories']);if($cat&&$cat!=='all'&&!in_array($cat,$cats,true))continue;if($q&&strpos(strtolower(implode(' ',[$x['id'],$x['title'],$x['subtype'],implode(' ',$x['categories'])])),$q)===false)continue;$f[]=$x;}usort($f,static fn($a,$b)=>strcasecmp($a['title'],$b['title']));$total=count($f);$items=array_slice($f,($page-1)*$pp,$pp);$cats=$type==='section'?self::categories($lib['sectionsCategories']??[]):($type==='page'?self::categories($lib['pagesCategories']??[]):['section'=>self::categories($lib['sectionsCategories']??[]),'page'=>self::categories($lib['pagesCategories']??[])]);return new WP_REST_Response(['type'=>$type,'q'=>$q,'category'=>$cat,'page'=>$page,'per_page'=>$pp,'total'=>$total,'total_pages'=>max(1,(int)ceil($total/$pp)),'available_categories'=>$cats,'templates'=>$items],200);}
	private static function append_templates(array &$o,$src,string $kind):void{if(!is_array($src))return;foreach($src as $r){if(!is_array($r)||empty($r['id']))continue;$id=(string)$r['id'];$k=$kind.'|'.$id;$c=[];foreach((array)($r['categories']??[]) as $v)if(is_string($v)&&trim($v)!=='')$c[]=strtolower(trim($v));if(isset($o[$k])){$o[$k]['categories']=array_values(array_unique(array_merge($o[$k]['categories'],$c)));continue;}$o[$k]=['id'=>$id,'kind'=>$kind,'title'=>(string)($r['title']??$id),'thumbnail'=>isset($r['thumbnail'])?esc_url_raw((string)$r['thumbnail']):null,'preview_url'=>isset($r['url'])?esc_url_raw((string)$r['url']):null,'pixfort_type'=>$r['type']??null,'subtype'=>$r['subtype']??null,'categories'=>array_values(array_unique($c)),'container_based'=>!empty($r['container_based'])];}}
	private static function categories($src):array{$o=[];if(!is_array($src))return$o;foreach($src as $r){if(!is_array($r)||empty($r['id']))continue;$o[]=['id'=>(string)$r['id'],'title'=>(string)($r['title']??$r['id']),'number'=>isset($r['number'])?absint($r['number']):null];}return$o;}
	private static function library(){static $cache=null;if(is_array($cache))return$cache;if(!function_exists('pixfort_elementor_library_data')&&file_exists(self::library_loader()))require_once self::library_loader();if(!function_exists('pixfort_elementor_library_data'))return new WP_Error('elementize_pixfort_library_unavailable','The active theme does not expose the Pixfort Elementor template library.',['status'=>503]);try{$x=pixfort_elementor_library_data();}catch(Throwable $e){return new WP_Error('elementize_pixfort_library_failed','Pixfort could not load its Elementor template catalogue: '.$e->getMessage(),['status'=>500]);}if(!is_array($x)||!isset($x['sections'],$x['pages']))return new WP_Error('elementize_pixfort_library_invalid','Pixfort returned an invalid template catalogue.',['status'=>500]);return $cache=$x;}
	private static function library_loader():string{return trailingslashit(get_template_directory()).'inc/demo-content/elementor/loader.php';}
	private static function source_path():string{return defined('PIXFORT_PLUGIN_DIR')?trailingslashit(PIXFORT_PLUGIN_DIR).'includes/import/elementor/source.php':'';}

	public static function insert_template(WP_REST_Request $r){$id=absint($r['id']);$tid=sanitize_key((string)$r->get_param('template_id'));if(!$tid)return new WP_Error('elementize_pixfort_template_required','template_id is required.',['status'=>400]);$d=self::need_doc($id);if(is_wp_error($d))return$d;$elements=$d->get_elements_data();if(!is_array($elements))return new WP_Error('elementize_invalid_elementor_data','Elementor returned invalid page data.',['status'=>500]);$h=self::hash($elements);if(!hash_equals($h,(string)$r->get_param('content_hash')))return new WP_Error('elementize_content_changed','The Elementor page changed after it was read. Read the page again before inserting a template.',['status'=>409,'content_hash'=>$h]);$ready=self::load_source();if(is_wp_error($ready))return$ready;add_filter('pixfort_el_remote_get_args',[self::class,'remote_headers'],100);try{$s=new \Elementor\TemplateLibrary\Source_Pixfort();$tpl=$s->get_data(['template_id'=>$tid,'editor_post_id'=>$id]);}catch(Throwable $e){return new WP_Error('elementize_pixfort_import_failed','Pixfort could not prepare the selected template: '.$e->getMessage(),['status'=>500]);}finally{remove_filter('pixfort_el_remote_get_args',[self::class,'remote_headers'],100);}if(is_wp_error($tpl))return new WP_Error('elementize_pixfort_import_failed',$tpl->get_error_message(),['status'=>502]);if(!is_array($tpl)||empty($tpl['content'])||!is_array($tpl['content']))return new WP_Error('elementize_pixfort_invalid_template','Pixfort returned no insertable Elementor content for this template.',['status'=>502]);$rev=self::revision($id);if(is_wp_error($rev))return$rev;$inserted=array_values($tpl['content']);$ids=[];foreach($inserted as $x)if(is_array($x)&&!empty($x['id']))$ids[]=(string)$x['id'];$elements=array_merge($elements,$inserted);try{$saved=$d->save(['elements'=>$elements]);}catch(Throwable $e){return new WP_Error('elementize_save_failed','Elementor could not save the Pixfort insertion: '.$e->getMessage(),['status'=>500]);}if(!$saved)return new WP_Error('elementize_save_failed','Elementor refused to save the Pixfort insertion.',['status'=>500]);$rd=self::doc($id);$re=$rd?$rd->get_elements_data():$elements;return new WP_REST_Response(['saved'=>true,'page_id'=>$id,'template_id'=>$tid,'template_title'=>$tpl['title']??null,'insert_position'=>'end','inserted_top_level_count'=>count($inserted),'inserted_top_level_ids'=>$ids,'revision_id'=>$rev,'content_hash'=>self::hash(is_array($re)?$re:$elements),'edit_url'=>$d->get_edit_url(),'permalink'=>get_permalink($id)],200);}
	private static function load_source(){if(!class_exists('\\Elementor\\Plugin'))return self::el_missing();if(!function_exists('pixfort_elementor_library_data')&&file_exists(self::library_loader()))require_once self::library_loader();if(!function_exists('pixfort_elementor_library_data'))return new WP_Error('elementize_pixfort_library_unavailable','The active theme does not expose the Pixfort Elementor template library.',['status'=>503]);$p=self::source_path();if(!$p||!file_exists($p))return new WP_Error('elementize_pixfort_source_unavailable','Pixfort Core template import source was not found.',['status'=>503]);if(!class_exists('\\Elementor\\TemplateLibrary\\Source_Base'))return new WP_Error('elementize_elementor_template_library_unavailable','Elementor template-library classes are not available.',['status'=>503]);if(!class_exists('\\Elementor\\TemplateLibrary\\Source_Pixfort',false))require_once$p;return class_exists('\\Elementor\\TemplateLibrary\\Source_Pixfort',false)?true:new WP_Error('elementize_pixfort_source_unavailable','Pixfort Core template import source could not be loaded.',['status'=>503]);}
	public static function remote_headers($a){if(!is_array($a))$a=[];$k=(string)get_option('envato_purchase_code_27889640','');if(trim($k)==='')return$a;$h=is_array($a['headers']??null)?$a['headers']:[];$h['pix_domain']=site_url();$h['purchase_key']=$k;$a['headers']=$h;return$a;}

	public static function page_text(WP_REST_Request $r){$id=absint($r['id']);$d=self::need_doc($id);if(is_wp_error($d))return$d;$e=$d->get_elements_data();if(!is_array($e))return new WP_Error('elementize_invalid_elementor_data','Elementor returned invalid page data.',['status'=>500]);$items=[];self::collect($e,$items);$p=get_post($id);return new WP_REST_Response(['page'=>['id'=>$id,'title'=>get_the_title($id),'status'=>$p->post_status,'modified_gmt'=>$p->post_modified_gmt,'edit_url'=>$d->get_edit_url(),'permalink'=>get_permalink($id)],'content_hash'=>self::hash($e),'text_items'=>$items],200);}
	public static function update_text(WP_REST_Request $r){$id=absint($r['id']);$d=self::need_doc($id);if(is_wp_error($d))return$d;$e=$d->get_elements_data();if(!is_array($e))return new WP_Error('elementize_invalid_elementor_data','Elementor returned invalid page data.',['status'=>500]);$h=self::hash($e);if(!hash_equals($h,(string)$r->get_param('content_hash')))return new WP_Error('elementize_content_changed','The Elementor page changed after it was read. Read the page again before applying edits.',['status'=>409,'content_hash'=>$h]);$u=$r->get_param('updates');if(!is_array($u)||!$u)return new WP_Error('elementize_updates_required','At least one text update is required.',['status'=>400]);if(count($u)>self::MAX_UPDATES)return new WP_Error('elementize_too_many_updates','Send at most '.self::MAX_UPDATES.' text updates per request.',['status'=>400]);$chg=[];foreach($u as $i=>$x){$v=self::validate($x,$i);if(is_wp_error($v))return$v;$old=null;$new=wp_kses_post((string)$x['value']);$res=self::apply($e,(string)$x['element_id'],$x['setting_path'],$new,array_key_exists('expected_value',$x)?(string)$x['expected_value']:null,$old);if(is_wp_error($res))return$res;if($res===false)return new WP_Error('elementize_element_not_found','The requested Elementor element no longer exists.',['status'=>409]);$chg[]=['element_id'=>(string)$x['element_id'],'setting_path'=>array_values($x['setting_path']),'old_value'=>$old,'new_value'=>$new];}$rev=self::revision($id);if(is_wp_error($rev))return$rev;try{$saved=$d->save(['elements'=>$e]);}catch(Throwable $ex){return new WP_Error('elementize_save_failed','Elementor could not save the page: '.$ex->getMessage(),['status'=>500]);}if(!$saved)return new WP_Error('elementize_save_failed','Elementor refused to save the page.',['status'=>500]);$rd=self::doc($id);$re=$rd?$rd->get_elements_data():$e;return new WP_REST_Response(['saved'=>true,'page_id'=>$id,'updated_count'=>count($chg),'revision_id'=>$rev,'content_hash'=>self::hash(is_array($re)?$re:$e),'changes'=>$chg,'edit_url'=>$d->get_edit_url(),'permalink'=>get_permalink($id)],200);}
	private static function revision(int $id){$p=get_post($id);if(!$p||!post_type_supports($p->post_type,'revisions')||!wp_revisions_enabled($p))return null;add_filter('wp_save_post_revision_check_for_changes','__return_false',PHP_INT_MAX);try{$x=wp_save_post_revision($id);}finally{remove_filter('wp_save_post_revision_check_for_changes','__return_false',PHP_INT_MAX);}return is_int($x)&&$x>0?$x:new WP_Error('elementize_revision_failed','Elementize could not create a pre-change revision, so the page was not modified.',['status'=>500]);}
	private static function validate($x,int $i){if(!is_array($x))return self::bad($i,'Each update must be an object.');if(empty($x['element_id'])||!is_string($x['element_id']))return self::bad($i,'element_id is required.');if(empty($x['setting_path'])||!is_array($x['setting_path']))return self::bad($i,'setting_path must be a non-empty array.');if(!array_key_exists('value',$x)||!is_string($x['value']))return self::bad($i,'value must be a string.');if(strlen($x['value'])>self::MAX_TEXT)return self::bad($i,'value is too long.');if(array_key_exists('expected_value',$x)&&!is_string($x['expected_value']))return self::bad($i,'expected_value must be a string when provided.');return true;}
	private static function bad(int $i,string $m):WP_Error{return new WP_Error('elementize_invalid_update','Invalid update at index '.$i.': '.$m,['status'=>400]);}
	private static function apply(array &$e,string $id,array $path,string $new,?string $expected,?string &$old){foreach($e as &$x){if(!is_array($x))continue;if(isset($x['id'])&&(string)$x['id']===$id){if(!isset($x['settings'])||!is_array($x['settings']))return new WP_Error('elementize_setting_not_found','The target Elementor element has no editable settings.',['status'=>400]);$c=&$x['settings'];foreach($path as $s){if(!is_string($s)&&!is_int($s))return new WP_Error('elementize_invalid_setting_path','Each setting_path segment must be a string or integer.',['status'=>400]);if(!is_array($c)||!array_key_exists($s,$c))return new WP_Error('elementize_setting_not_found','The requested text setting no longer exists.',['status'=>409]);$c=&$c[$s];}if(!is_string($c)||!self::copy_field($path,$c))return new WP_Error('elementize_not_copy_field','Elementize only permits text updates to recognized copy fields in this build.',['status'=>400]);if($expected!==null&&$c!==$expected)return new WP_Error('elementize_value_changed','The target text changed after it was read.',['status'=>409]);$old=$c;$c=$new;return true;}if(!empty($x['elements'])&&is_array($x['elements'])){$z=self::apply($x['elements'],$id,$path,$new,$expected,$old);if($z===true||is_wp_error($z))return$z;}}unset($x);return false;}
	private static function collect(array $e,array &$items):void{foreach($e as $x){if(!is_array($x))continue;$id=(string)($x['id']??'');$et=$x['elType']??null;$wt=$x['widgetType']??null;if($id&&!empty($x['settings'])&&is_array($x['settings']))self::collect_settings($x['settings'],[],$id,$et,$wt,$items);if(!empty($x['elements'])&&is_array($x['elements']))self::collect($x['elements'],$items);}}
	private static function collect_settings($v,array $p,string $id,?string $et,?string $wt,array &$items):void{if(is_array($v)){foreach($v as $k=>$n)self::collect_settings($n,array_merge($p,[$k]),$id,$et,$wt,$items);return;}if(!is_string($v)||!self::copy_field($p,$v))return;$items[]=['element_id'=>$id,'element_type'=>$et,'widget_type'=>$wt,'setting_path'=>array_values($p),'format'=>wp_strip_all_tags($v)===$v?'text':'html','value'=>$v];}
	private static function copy_field(array $p,string $v):bool{if(trim($v)===''||strlen($v)>self::MAX_TEXT||str_starts_with(ltrim($v),'[elementor-tag'))return false;$k='';for($i=count($p)-1;$i>=0;$i--)if(is_string($p[$i])){$k=strtolower($p[$i]);break;}if(!$k)return false;if(preg_match('/(^|_)(url|link|href|src|id|class|selector|shortcode|icon|image|media|color|background|gradient|font|typography|size|width|height|margin|padding|border|radius|opacity|align|position|offset|z_index|animation|transition|transform|query|taxonomy|post_id)(_|$)/i',$k))return false;return(bool)preg_match('/(^|_)(title|text|content|editor|description|heading|headline|subtitle|sub_title|label|caption|button_text|btn_text|placeholder|prefix|suffix|message)(_|$)/i',$k);}

	private static function need_doc(int $id){if(!class_exists('\\Elementor\\Plugin'))return self::el_missing();$d=self::doc($id);if(!$d)return new WP_Error('elementize_elementor_document_not_found','Elementor could not load this page as a document.',['status'=>404]);if(!$d->is_built_with_elementor())return new WP_Error('elementize_not_elementor_page','This page is not currently built with Elementor.',['status'=>400]);return$d;}
	private static function doc(int $id){try{return \Elementor\Plugin::$instance->documents->get($id);}catch(Throwable $e){return null;}}
	private static function hash(array $e):string{$j=wp_json_encode($e,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);return hash('sha256',$j===false?'':$j);}
	private static function el_missing():WP_Error{return new WP_Error('elementize_elementor_required','Elementor must be installed and active.',['status'=>503]);}
}
Elementize_Plugin::init();
}
